### PR TITLE
Introduce prop-types

### PR DESCRIPTION
**Pull request by yesmeck**

### CODE REVIEW

**Comment by yesmeck** [comment]
@afc163

**Comment by afc163** [comment]
https://github.com/react-component/cascader/blob/master/tests/index.spec.js#L4 这里一并改下。

**Comment by yesmeck** [comment]
Done.

**Comment by afc163** [comment]
```
$ npm owner ls rc-cascader 
afc163 <afc163@gmail.com>
yesmeck <yesmeck@gmail.com>
```

**Pull request merged**
