### PR TITLE
fix: multiple mode lose indeterminate except first-level

### PR DESCRIPTION
**Pull request by horseson2018**
解决了[issue](https://github.com/react-component/cascader/issues/228)的问题

### CODE REVIEW

**Comment by afc163** [comment]
来个测试用例？

**Comment by horseson2018** [comment]
> 来个测试用例？

```javascript
import React from 'react';
import Cascader from '../src';

const addressOptions = [
  {
    label: '浙江',
    value: 'zj',
    children: [
      {
        label: '杭州',
        value: 'hangzhou',
        children: [
          {
            label: '富阳',
            value: 'fuyang',
          },
          {
            label: '余杭',
            value: 'yuhang',
          },
        ],
      },
    ],
  },
];

const Demo = () => {
  return (
    <>
      <Cascader style={{ width: 200 }} options={addressOptions} checkable={true} allowClear />
    </>
  );
};

export default Demo;

**Comment by horseson2018** [comment]
> 来个测试用例？

```typescript
import React from 'react';
import Cascader from '../src';

const addressOptions = [
  {
    label: '浙江',
    value: 'zj',
    children: [
      {
        label: '杭州',
        value: 'hangzhou',
        children: [
          {
            label: '富阳',
            value: 'fuyang',
          },
          {
            label: '余杭',
            value: 'yuhang',
          },
        ],
      },
    ],
  },
];

const Demo = () => {
  return (
    <>
      <Cascader style={{ width: 200 }} options={addressOptions} checkable={true} allowClear />
    </>
  );
};

export default Demo;

**Comment by afc163** [comment]
我指的是 test case：https://github.com/react-component/cascader/blob/master/tests/selector.spec.tsx

**Comment by horseson2018** [comment]
> 我指的是 test case：https://github.com/react-component/cascader/blob/master/tests/selector.spec.tsx

😅误会了，已补充

**Pull request merged**
